### ISSUE TITLE
SyntaxError

### ISSUE THREAD

**Issue by bitwombat** [casey/reap.vim#2]
Hitting `==` on a `1+1` line, I'm getting a `SyntaxError: invalid syntax` at

https://github.com/casey/reap.vim/blob/master/reap.py#L110

/usr/bin/python3 is python3.5.

**Comment by casey** [comment]
I'm using f-string syntax, which is new in Python 3.6. I'll change it to use `.format`, which should work with 3.5. I should probably figure out what the minimum supported python version is.

**Comment by casey** [comment]
Check out #3, which I just opened. Unfortunately, the ast module that python uses isn't stable between versions, so as written it's currently only compatible with Python 3.7. ;_;
